project:

  type: website

website:

  title: "DDRP Pest Trends"
  
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "DDRP Map"
        href: maps.qmd
      - text: "Pest Reports"
        href: reports.qmd
        
  page-footer: 
    right: 
      - href: https://quarto.org/
        text: "Made with Quarto"
      - href: https://github.com/bbarker505/DDRP_pest_trends
        icon: github

format:

  html:
  
    theme:
      - sandstone
      
    css: styles.css
    
    toc: false

execute:

  freeze: auto
